language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"

install: pip install . --use-mirrors

script:
  - python -c "import sys; sys.exit(0 if sys.version_info[0]<3 else 1)" && 2to3 -w tests || true
  - python setup.py test

notifications:
  email:
    - hongqn@douban.com
